name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t github-actions-docker .

      - name: Run Docker container
        run: |
          docker run -d \
            --name github-actions-container \
            -p 8080:80 \
            github-actions-docker

      - name: Test container
        run: |
          sleep 5
          curl --fail http://localhost:8080

      - name: Stop container
        run: |
          docker stop github-actions-container
          docker rm github-actions-container
